name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew zipDist
    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
        name: spm-1.6.5.zip
        path: releases
