package nl.astraeus.spm.model

import nl.astraeus.database.Dao
import nl.astraeus.database.annotations.*
import java.util.*

/**
 * User: rnentjes
 * Date: 20-11-16
 * Time: 13:01
 */

@Table(name = "groups")
@Cache(maxSize = 5000)
data class Group(
  @Id(IdType.AUTOGENERATED) var id: Long = 0,
  @Index var user: String,
  @Index var parent: String,
  var name: String,

  var created: Date,
  var updated: Date
) {
    constructor(): this(0, "", "", "", Date(), Date())
}

object GroupDao: Dao<Group>(Group::class.java) {

    fun findByUser(email: String) = where("user = ?", email)

}
