package nl.astraeus.spm.model

import nl.astraeus.database.Dao
import nl.astraeus.database.annotations.*
import java.util.*

/**
 * User: rnentjes
 * Date: 20-11-16
 * Time: 12:58
 */

@Table(name = "passwords")
@Cache(maxSize = 5000)
data class Password(
  @Id(IdType.AUTOGENERATED) var id: Long = 0,
  @Index var user: String,
  @Index var group: String,
  var name: String,
  var website: String,
  var username: String,
  var password: String,
  @Blob var description: String,
  var created: Date,
  var updated: Date
) {
    constructor(): this(0, "", "", "", "", "", "", "", Date(), Date())
}

object PasswordDao: Dao<Password>(Password::class.java) {

    fun findByUser(email: String) = where("user = ?", email)

}
