package nl.astraeus.spm.model

import nl.astraeus.database.SimpleDao
import nl.astraeus.database.annotations.*
import nl.astraeus.spm.util.Tokenizer
import java.util.*

/**
 * User: rnentjes
 * Date: 20-11-16
 * Time: 12:58
 */

@Table(name = "passwords")
@Cache(maxSize = 5000)
data class Password(
  @Id(IdType.AUTOGENERATED) var id: Long = 0,
  @Index var user: String,
  @Index var parentGroup: Long,
  var name: String,
  var website: String,
  var username: String,
  var password: String,
  @Serialized var description: String,
  var created: Date,
  var updated: Date
) {
    constructor(): this(0, "", 0, "", "", "", "", "", Date(), Date())

    fun tokenize(): String {
        return Tokenizer.tokenize("$id", user, "$parentGroup", name, website, username, password, description)
    }
}

object PasswordDao: SimpleDao<Password>(Password::class.java) {

    fun findByUser(email: String) = where("user = ?", email)

    fun findByGroup(groupId: Long) = where("parentGroup = ?", groupId)

}
