package nl.astraeus.spm.model

import nl.astraeus.database.Dao
import nl.astraeus.database.annotations.*
import java.text.SimpleDateFormat
import java.util.*

/**
 * User: rnentjes
 * Date: 20-11-16
 * Time: 12:54
 */

@Table(name = "usrs")
@Cache(maxSize = 5000)
data class User(
  @Id(IdType.AUTOGENERATED) var id: Long = 0,
  @Index var email: String,
  var password: String,
  var encryptedKey: String,
  var name: String,
  var created: Date,
  var updated: Date
) {
    constructor(email: String, name: String): this(0, email, "", "", name, Date(), Date())

    constructor(): this(0, "", "", "", "", Date(), Date())

    fun checkPassword(password: String) = (password == this.password)
}

object UserDao: Dao<User>(User::class.java) {

    fun findByEmail(email: String) = find("email = ?", email)

}
