package nl.astraeus.spm.model

import nl.astraeus.database.Dao
import nl.astraeus.database.annotations.*
import java.util.*

/**
 * User: rnentjes
 * Date: 20-11-16
 * Time: 12:54
 */

@Table(name = "usrs")
@Cache(maxSize = 5000)
data class User(
  @Id(IdType.AUTOGENERATED) var id: Long = 0,
  var password: String,
  var encryptedKey: String,
  @Index var name: String,
  var created: Date,
  var updated: Date
) {
    constructor(name: String, password: String, encryptedKey: String): this(0, password, encryptedKey, name, Date(), Date())

    constructor(): this(0, "", "", "", Date(), Date())

    fun checkPassword(password: String) = (password == this.password)
}

object UserDao: Dao<User>(User::class.java) {

    fun findByName(name: String) = find("name = ?", name)

}
